micronaut:
  application:
    name: service-x
  server:
    port: 8083
  security:
    enabled: true
    token:
      jwt:
        signatures:
          jwks:
            jwks-generator-a:
              keyType: 'EC'
              url: 'http://localhost:8081/.well-known/jwks.json'
            jwks-generator-b:
              keyType: 'EC'
              url: 'http://localhost:8082/.well-known/jwks.json'